version: '3'

services:
  pg-prod:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}

  pg-dev:
    image: bitnami/postgresql
    ports:
      - 5431:5432
    environment:
      - POSTGRESQL_USERNAME=${DB_USER_DEV}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD_DEV}
      - POSTGRESQL_DATABASE=${DB_NAME_DEV}
