version: '3'

services:
  expense-tracker:
    image: bitnami/postgresql
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}

