# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Expense Tracker CI Integration

on:
  pull_request:
    branches:
      - master

jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: run install and build
        run: |
          yarn
          yarn start

      - name: test coverage
        run: |
          yarn test:cov

      - name: validate test coverage
        run: |
          coverage=$(cat coverage/coverage-summary.json | jq -r '.total.lines.pct')
          min_coverage=80
          if (( $(echo "$coverage < $min_coverage" | bc -l) )); then
            echo "O coverage de testes é $coverage e é inferior a $min_coverage%. Abortando o pull request."
            exit 1
          fi
