name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Create .env file
        run: |
          echo "NODE_ENV=prod" > .env
          echo "SERVER_PORT=8080" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_USER=academy" >> .env
          echo "DB_PASSWORD=academy" >> .env
          echo "DB_NAME=expense-tracker" >> .env
          echo "SERVER_PORT=8080" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_USER=academy-dev" >> .env
          echo "DB_PASSWORD=academy-dev" >> .env
          echo "DB_NAME=expense-tracker-dev" >> .env

      - name: Install Docker Compose
        run: |
          sudo apt-get -y update
          sudo apt-get -y install docker-compose

      - name: Start services with Docker Compose
        run: |
          sudo docker-compose up -d

      - run: 'yarn install --frozen-lockfile'

      - run: 'yarn test:unit -u'

      - name: run install and build
        run: |
          yarn
          yarn start

      - name: Test coverage
        run: |
          yarn test:cov

      
      - name: Stop and remove services with Docker Compose
        run: |
          sudo docker-compose down

